 /* generated by ResBuilder, (c)2003 Actions */
/******************************************/
#ifndef _LANG_ID
#define _LANG_ID

/*#define ENGLISH  							0
#define FRENCH 								1
#define GERMAN             		2
#define ITALIAN            		3
#define SPANISH              	4
#define PORTUGUESE            5
#define POLISH              	6
#define RUSSIAN             	7
#define CHINESE_SIMPLIFIED    8
#define CHINESE_TRADITIONAL   9
#define JAPANESE             		10
#define SWEDISH             		11
#define CZECH               		12
#define DANISH              		13
#define KOREAN              		14
#define DUTCH             		15
#define TURKISH             		16
#define HEBREW              		17
#define THAI                		18
#define HUNGARIAN           		19
#define ROMANIAN            		20
#define ARABIC              		21
#define INDONESIAN          		22
#define GREEK               		23*/



#define CHINESE_SIMPLIFIED  		0
#define CHINESE_TRADITIONAL 		1
#define ENGLISH             		2
#define JAPANESE            		3
#define KOREAN              		4
#define FRENCH              		5
#define GERMAN              		6
#define ITALIAN             		7
#define DUTCH               		8
#define PORTUGUESE          		9
#define SPANISH             		10
#define SWEDISH             		11
#define CZECH               		12
#define DANISH              		13
#define POLISH              		14
#define RUSSIAN             		15
#define TURKISH             		16
#define HEBREW              		17
#define THAI                		18
#define HUNGARIAN           		19
#define ROMANIAN            		20
#define ARABIC              		21
#define INDONESIAN          		22
#define GREEK               		23
#define NORWEGIAN                   24
#define BULGARIAN           		25
#define SLOVAK              		26
#define UKRAINIAN                   27
#define CROATIA                     28
#define LITHUANIAN                  29
#define ESTONIAN                    30
#define LATVIAN                     31
#define SERBIAN                     32

#endif